// Code generated by protoc-gen-go. DO NOT EDIT.
// source: orc_proto.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CompressionKind int32

const (
	CompressionKind_NONE   CompressionKind = 0
	CompressionKind_ZLIB   CompressionKind = 1
	CompressionKind_SNAPPY CompressionKind = 2
	CompressionKind_LZO    CompressionKind = 3
	CompressionKind_LZ4    CompressionKind = 4
	CompressionKind_ZSTD   CompressionKind = 5
)

var CompressionKind_name = map[int32]string{
	0: "NONE",
	1: "ZLIB",
	2: "SNAPPY",
	3: "LZO",
	4: "LZ4",
	5: "ZSTD",
}

var CompressionKind_value = map[string]int32{
	"NONE":   0,
	"ZLIB":   1,
	"SNAPPY": 2,
	"LZO":    3,
	"LZ4":    4,
	"ZSTD":   5,
}

func (x CompressionKind) Enum() *CompressionKind {
	p := new(CompressionKind)
	*p = x
	return p
}

func (x CompressionKind) String() string {
	return proto.EnumName(CompressionKind_name, int32(x))
}

func (x *CompressionKind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CompressionKind_value, data, "CompressionKind")
	if err != nil {
		return err
	}
	*x = CompressionKind(value)
	return nil
}

func (CompressionKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{0}
}

// if you add new index stream kinds, you need to make sure to update
// StreamName to ensure it is added to the stripe in the right area
type Stream_Kind int32

const (
	Stream_PRESENT           Stream_Kind = 0
	Stream_DATA              Stream_Kind = 1
	Stream_LENGTH            Stream_Kind = 2
	Stream_DICTIONARY_DATA   Stream_Kind = 3
	Stream_DICTIONARY_COUNT  Stream_Kind = 4
	Stream_SECONDARY         Stream_Kind = 5
	Stream_ROW_INDEX         Stream_Kind = 6
	Stream_BLOOM_FILTER      Stream_Kind = 7
	Stream_BLOOM_FILTER_UTF8 Stream_Kind = 8
)

var Stream_Kind_name = map[int32]string{
	0: "PRESENT",
	1: "DATA",
	2: "LENGTH",
	3: "DICTIONARY_DATA",
	4: "DICTIONARY_COUNT",
	5: "SECONDARY",
	6: "ROW_INDEX",
	7: "BLOOM_FILTER",
	8: "BLOOM_FILTER_UTF8",
}

var Stream_Kind_value = map[string]int32{
	"PRESENT":           0,
	"DATA":              1,
	"LENGTH":            2,
	"DICTIONARY_DATA":   3,
	"DICTIONARY_COUNT":  4,
	"SECONDARY":         5,
	"ROW_INDEX":         6,
	"BLOOM_FILTER":      7,
	"BLOOM_FILTER_UTF8": 8,
}

func (x Stream_Kind) Enum() *Stream_Kind {
	p := new(Stream_Kind)
	*p = x
	return p
}

func (x Stream_Kind) String() string {
	return proto.EnumName(Stream_Kind_name, int32(x))
}

func (x *Stream_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Stream_Kind_value, data, "Stream_Kind")
	if err != nil {
		return err
	}
	*x = Stream_Kind(value)
	return nil
}

func (Stream_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{13, 0}
}

type ColumnEncoding_Kind int32

const (
	ColumnEncoding_DIRECT        ColumnEncoding_Kind = 0
	ColumnEncoding_DICTIONARY    ColumnEncoding_Kind = 1
	ColumnEncoding_DIRECT_V2     ColumnEncoding_Kind = 2
	ColumnEncoding_DICTIONARY_V2 ColumnEncoding_Kind = 3
)

var ColumnEncoding_Kind_name = map[int32]string{
	0: "DIRECT",
	1: "DICTIONARY",
	2: "DIRECT_V2",
	3: "DICTIONARY_V2",
}

var ColumnEncoding_Kind_value = map[string]int32{
	"DIRECT":        0,
	"DICTIONARY":    1,
	"DIRECT_V2":     2,
	"DICTIONARY_V2": 3,
}

func (x ColumnEncoding_Kind) Enum() *ColumnEncoding_Kind {
	p := new(ColumnEncoding_Kind)
	*p = x
	return p
}

func (x ColumnEncoding_Kind) String() string {
	return proto.EnumName(ColumnEncoding_Kind_name, int32(x))
}

func (x *ColumnEncoding_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ColumnEncoding_Kind_value, data, "ColumnEncoding_Kind")
	if err != nil {
		return err
	}
	*x = ColumnEncoding_Kind(value)
	return nil
}

func (ColumnEncoding_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{14, 0}
}

type Type_Kind int32

const (
	Type_BOOLEAN   Type_Kind = 0
	Type_BYTE      Type_Kind = 1
	Type_SHORT     Type_Kind = 2
	Type_INT       Type_Kind = 3
	Type_LONG      Type_Kind = 4
	Type_FLOAT     Type_Kind = 5
	Type_DOUBLE    Type_Kind = 6
	Type_STRING    Type_Kind = 7
	Type_BINARY    Type_Kind = 8
	Type_TIMESTAMP Type_Kind = 9
	Type_LIST      Type_Kind = 10
	Type_MAP       Type_Kind = 11
	Type_STRUCT    Type_Kind = 12
	Type_UNION     Type_Kind = 13
	Type_DECIMAL   Type_Kind = 14
	Type_DATE      Type_Kind = 15
	Type_VARCHAR   Type_Kind = 16
	Type_CHAR      Type_Kind = 17
)

var Type_Kind_name = map[int32]string{
	0:  "BOOLEAN",
	1:  "BYTE",
	2:  "SHORT",
	3:  "INT",
	4:  "LONG",
	5:  "FLOAT",
	6:  "DOUBLE",
	7:  "STRING",
	8:  "BINARY",
	9:  "TIMESTAMP",
	10: "LIST",
	11: "MAP",
	12: "STRUCT",
	13: "UNION",
	14: "DECIMAL",
	15: "DATE",
	16: "VARCHAR",
	17: "CHAR",
}

var Type_Kind_value = map[string]int32{
	"BOOLEAN":   0,
	"BYTE":      1,
	"SHORT":     2,
	"INT":       3,
	"LONG":      4,
	"FLOAT":     5,
	"DOUBLE":    6,
	"STRING":    7,
	"BINARY":    8,
	"TIMESTAMP": 9,
	"LIST":      10,
	"MAP":       11,
	"STRUCT":    12,
	"UNION":     13,
	"DECIMAL":   14,
	"DATE":      15,
	"VARCHAR":   16,
	"CHAR":      17,
}

func (x Type_Kind) Enum() *Type_Kind {
	p := new(Type_Kind)
	*p = x
	return p
}

func (x Type_Kind) String() string {
	return proto.EnumName(Type_Kind_name, int32(x))
}

func (x *Type_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Type_Kind_value, data, "Type_Kind")
	if err != nil {
		return err
	}
	*x = Type_Kind(value)
	return nil
}

func (Type_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{16, 0}
}

type IntegerStatistics struct {
	Minimum              *int64   `protobuf:"zigzag64,1,opt,name=minimum" json:"minimum,omitempty"`
	Maximum              *int64   `protobuf:"zigzag64,2,opt,name=maximum" json:"maximum,omitempty"`
	Sum                  *int64   `protobuf:"zigzag64,3,opt,name=sum" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntegerStatistics) Reset()         { *m = IntegerStatistics{} }
func (m *IntegerStatistics) String() string { return proto.CompactTextString(m) }
func (*IntegerStatistics) ProtoMessage()    {}
func (*IntegerStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{0}
}

func (m *IntegerStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegerStatistics.Unmarshal(m, b)
}
func (m *IntegerStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegerStatistics.Marshal(b, m, deterministic)
}
func (m *IntegerStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegerStatistics.Merge(m, src)
}
func (m *IntegerStatistics) XXX_Size() int {
	return xxx_messageInfo_IntegerStatistics.Size(m)
}
func (m *IntegerStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegerStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_IntegerStatistics proto.InternalMessageInfo

func (m *IntegerStatistics) GetMinimum() int64 {
	if m != nil && m.Minimum != nil {
		return *m.Minimum
	}
	return 0
}

func (m *IntegerStatistics) GetMaximum() int64 {
	if m != nil && m.Maximum != nil {
		return *m.Maximum
	}
	return 0
}

func (m *IntegerStatistics) GetSum() int64 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

type DoubleStatistics struct {
	Minimum              *float64 `protobuf:"fixed64,1,opt,name=minimum" json:"minimum,omitempty"`
	Maximum              *float64 `protobuf:"fixed64,2,opt,name=maximum" json:"maximum,omitempty"`
	Sum                  *float64 `protobuf:"fixed64,3,opt,name=sum" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleStatistics) Reset()         { *m = DoubleStatistics{} }
func (m *DoubleStatistics) String() string { return proto.CompactTextString(m) }
func (*DoubleStatistics) ProtoMessage()    {}
func (*DoubleStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{1}
}

func (m *DoubleStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleStatistics.Unmarshal(m, b)
}
func (m *DoubleStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleStatistics.Marshal(b, m, deterministic)
}
func (m *DoubleStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleStatistics.Merge(m, src)
}
func (m *DoubleStatistics) XXX_Size() int {
	return xxx_messageInfo_DoubleStatistics.Size(m)
}
func (m *DoubleStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleStatistics proto.InternalMessageInfo

func (m *DoubleStatistics) GetMinimum() float64 {
	if m != nil && m.Minimum != nil {
		return *m.Minimum
	}
	return 0
}

func (m *DoubleStatistics) GetMaximum() float64 {
	if m != nil && m.Maximum != nil {
		return *m.Maximum
	}
	return 0
}

func (m *DoubleStatistics) GetSum() float64 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

type StringStatistics struct {
	Minimum *string `protobuf:"bytes,1,opt,name=minimum" json:"minimum,omitempty"`
	Maximum *string `protobuf:"bytes,2,opt,name=maximum" json:"maximum,omitempty"`
	// sum will store the total length of all strings in a stripe
	Sum *int64 `protobuf:"zigzag64,3,opt,name=sum" json:"sum,omitempty"`
	// If the minimum or maximum value was longer than 1024 bytes, store a lower or upper
	// bound instead of the minimum or maximum values above.
	LowerBound           *string  `protobuf:"bytes,4,opt,name=lowerBound" json:"lowerBound,omitempty"`
	UpperBound           *string  `protobuf:"bytes,5,opt,name=upperBound" json:"upperBound,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringStatistics) Reset()         { *m = StringStatistics{} }
func (m *StringStatistics) String() string { return proto.CompactTextString(m) }
func (*StringStatistics) ProtoMessage()    {}
func (*StringStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{2}
}

func (m *StringStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringStatistics.Unmarshal(m, b)
}
func (m *StringStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringStatistics.Marshal(b, m, deterministic)
}
func (m *StringStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringStatistics.Merge(m, src)
}
func (m *StringStatistics) XXX_Size() int {
	return xxx_messageInfo_StringStatistics.Size(m)
}
func (m *StringStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_StringStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_StringStatistics proto.InternalMessageInfo

func (m *StringStatistics) GetMinimum() string {
	if m != nil && m.Minimum != nil {
		return *m.Minimum
	}
	return ""
}

func (m *StringStatistics) GetMaximum() string {
	if m != nil && m.Maximum != nil {
		return *m.Maximum
	}
	return ""
}

func (m *StringStatistics) GetSum() int64 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

func (m *StringStatistics) GetLowerBound() string {
	if m != nil && m.LowerBound != nil {
		return *m.LowerBound
	}
	return ""
}

func (m *StringStatistics) GetUpperBound() string {
	if m != nil && m.UpperBound != nil {
		return *m.UpperBound
	}
	return ""
}

type BucketStatistics struct {
	Count                []uint64 `protobuf:"varint,1,rep,packed,name=count" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BucketStatistics) Reset()         { *m = BucketStatistics{} }
func (m *BucketStatistics) String() string { return proto.CompactTextString(m) }
func (*BucketStatistics) ProtoMessage()    {}
func (*BucketStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{3}
}

func (m *BucketStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BucketStatistics.Unmarshal(m, b)
}
func (m *BucketStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BucketStatistics.Marshal(b, m, deterministic)
}
func (m *BucketStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BucketStatistics.Merge(m, src)
}
func (m *BucketStatistics) XXX_Size() int {
	return xxx_messageInfo_BucketStatistics.Size(m)
}
func (m *BucketStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_BucketStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_BucketStatistics proto.InternalMessageInfo

func (m *BucketStatistics) GetCount() []uint64 {
	if m != nil {
		return m.Count
	}
	return nil
}

type DecimalStatistics struct {
	Minimum              *string  `protobuf:"bytes,1,opt,name=minimum" json:"minimum,omitempty"`
	Maximum              *string  `protobuf:"bytes,2,opt,name=maximum" json:"maximum,omitempty"`
	Sum                  *string  `protobuf:"bytes,3,opt,name=sum" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecimalStatistics) Reset()         { *m = DecimalStatistics{} }
func (m *DecimalStatistics) String() string { return proto.CompactTextString(m) }
func (*DecimalStatistics) ProtoMessage()    {}
func (*DecimalStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{4}
}

func (m *DecimalStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecimalStatistics.Unmarshal(m, b)
}
func (m *DecimalStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecimalStatistics.Marshal(b, m, deterministic)
}
func (m *DecimalStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecimalStatistics.Merge(m, src)
}
func (m *DecimalStatistics) XXX_Size() int {
	return xxx_messageInfo_DecimalStatistics.Size(m)
}
func (m *DecimalStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_DecimalStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_DecimalStatistics proto.InternalMessageInfo

func (m *DecimalStatistics) GetMinimum() string {
	if m != nil && m.Minimum != nil {
		return *m.Minimum
	}
	return ""
}

func (m *DecimalStatistics) GetMaximum() string {
	if m != nil && m.Maximum != nil {
		return *m.Maximum
	}
	return ""
}

func (m *DecimalStatistics) GetSum() string {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return ""
}

type DateStatistics struct {
	// min,max values saved as days since epoch
	Minimum              *int32   `protobuf:"zigzag32,1,opt,name=minimum" json:"minimum,omitempty"`
	Maximum              *int32   `protobuf:"zigzag32,2,opt,name=maximum" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DateStatistics) Reset()         { *m = DateStatistics{} }
func (m *DateStatistics) String() string { return proto.CompactTextString(m) }
func (*DateStatistics) ProtoMessage()    {}
func (*DateStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{5}
}

func (m *DateStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DateStatistics.Unmarshal(m, b)
}
func (m *DateStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DateStatistics.Marshal(b, m, deterministic)
}
func (m *DateStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DateStatistics.Merge(m, src)
}
func (m *DateStatistics) XXX_Size() int {
	return xxx_messageInfo_DateStatistics.Size(m)
}
func (m *DateStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_DateStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_DateStatistics proto.InternalMessageInfo

func (m *DateStatistics) GetMinimum() int32 {
	if m != nil && m.Minimum != nil {
		return *m.Minimum
	}
	return 0
}

func (m *DateStatistics) GetMaximum() int32 {
	if m != nil && m.Maximum != nil {
		return *m.Maximum
	}
	return 0
}

type TimestampStatistics struct {
	// min,max values saved as milliseconds since epoch
	Minimum              *int64   `protobuf:"zigzag64,1,opt,name=minimum" json:"minimum,omitempty"`
	Maximum              *int64   `protobuf:"zigzag64,2,opt,name=maximum" json:"maximum,omitempty"`
	MinimumUtc           *int64   `protobuf:"zigzag64,3,opt,name=minimumUtc" json:"minimumUtc,omitempty"`
	MaximumUtc           *int64   `protobuf:"zigzag64,4,opt,name=maximumUtc" json:"maximumUtc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimestampStatistics) Reset()         { *m = TimestampStatistics{} }
func (m *TimestampStatistics) String() string { return proto.CompactTextString(m) }
func (*TimestampStatistics) ProtoMessage()    {}
func (*TimestampStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{6}
}

func (m *TimestampStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimestampStatistics.Unmarshal(m, b)
}
func (m *TimestampStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimestampStatistics.Marshal(b, m, deterministic)
}
func (m *TimestampStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimestampStatistics.Merge(m, src)
}
func (m *TimestampStatistics) XXX_Size() int {
	return xxx_messageInfo_TimestampStatistics.Size(m)
}
func (m *TimestampStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_TimestampStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_TimestampStatistics proto.InternalMessageInfo

func (m *TimestampStatistics) GetMinimum() int64 {
	if m != nil && m.Minimum != nil {
		return *m.Minimum
	}
	return 0
}

func (m *TimestampStatistics) GetMaximum() int64 {
	if m != nil && m.Maximum != nil {
		return *m.Maximum
	}
	return 0
}

func (m *TimestampStatistics) GetMinimumUtc() int64 {
	if m != nil && m.MinimumUtc != nil {
		return *m.MinimumUtc
	}
	return 0
}

func (m *TimestampStatistics) GetMaximumUtc() int64 {
	if m != nil && m.MaximumUtc != nil {
		return *m.MaximumUtc
	}
	return 0
}

type BinaryStatistics struct {
	// sum will store the total binary blob length in a stripe
	Sum                  *int64   `protobuf:"zigzag64,1,opt,name=sum" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BinaryStatistics) Reset()         { *m = BinaryStatistics{} }
func (m *BinaryStatistics) String() string { return proto.CompactTextString(m) }
func (*BinaryStatistics) ProtoMessage()    {}
func (*BinaryStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{7}
}

func (m *BinaryStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryStatistics.Unmarshal(m, b)
}
func (m *BinaryStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryStatistics.Marshal(b, m, deterministic)
}
func (m *BinaryStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryStatistics.Merge(m, src)
}
func (m *BinaryStatistics) XXX_Size() int {
	return xxx_messageInfo_BinaryStatistics.Size(m)
}
func (m *BinaryStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryStatistics proto.InternalMessageInfo

func (m *BinaryStatistics) GetSum() int64 {
	if m != nil && m.Sum != nil {
		return *m.Sum
	}
	return 0
}

type ColumnStatistics struct {
	NumberOfValues       *uint64              `protobuf:"varint,1,opt,name=numberOfValues" json:"numberOfValues,omitempty"`
	IntStatistics        *IntegerStatistics   `protobuf:"bytes,2,opt,name=intStatistics" json:"intStatistics,omitempty"`
	DoubleStatistics     *DoubleStatistics    `protobuf:"bytes,3,opt,name=doubleStatistics" json:"doubleStatistics,omitempty"`
	StringStatistics     *StringStatistics    `protobuf:"bytes,4,opt,name=stringStatistics" json:"stringStatistics,omitempty"`
	BucketStatistics     *BucketStatistics    `protobuf:"bytes,5,opt,name=bucketStatistics" json:"bucketStatistics,omitempty"`
	DecimalStatistics    *DecimalStatistics   `protobuf:"bytes,6,opt,name=decimalStatistics" json:"decimalStatistics,omitempty"`
	DateStatistics       *DateStatistics      `protobuf:"bytes,7,opt,name=dateStatistics" json:"dateStatistics,omitempty"`
	BinaryStatistics     *BinaryStatistics    `protobuf:"bytes,8,opt,name=binaryStatistics" json:"binaryStatistics,omitempty"`
	TimestampStatistics  *TimestampStatistics `protobuf:"bytes,9,opt,name=timestampStatistics" json:"timestampStatistics,omitempty"`
	HasNull              *bool                `protobuf:"varint,10,opt,name=hasNull" json:"hasNull,omitempty"`
	BytesOnDisk          *uint64              `protobuf:"varint,11,opt,name=bytesOnDisk" json:"bytesOnDisk,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ColumnStatistics) Reset()         { *m = ColumnStatistics{} }
func (m *ColumnStatistics) String() string { return proto.CompactTextString(m) }
func (*ColumnStatistics) ProtoMessage()    {}
func (*ColumnStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{8}
}

func (m *ColumnStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnStatistics.Unmarshal(m, b)
}
func (m *ColumnStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnStatistics.Marshal(b, m, deterministic)
}
func (m *ColumnStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnStatistics.Merge(m, src)
}
func (m *ColumnStatistics) XXX_Size() int {
	return xxx_messageInfo_ColumnStatistics.Size(m)
}
func (m *ColumnStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnStatistics proto.InternalMessageInfo

func (m *ColumnStatistics) GetNumberOfValues() uint64 {
	if m != nil && m.NumberOfValues != nil {
		return *m.NumberOfValues
	}
	return 0
}

func (m *ColumnStatistics) GetIntStatistics() *IntegerStatistics {
	if m != nil {
		return m.IntStatistics
	}
	return nil
}

func (m *ColumnStatistics) GetDoubleStatistics() *DoubleStatistics {
	if m != nil {
		return m.DoubleStatistics
	}
	return nil
}

func (m *ColumnStatistics) GetStringStatistics() *StringStatistics {
	if m != nil {
		return m.StringStatistics
	}
	return nil
}

func (m *ColumnStatistics) GetBucketStatistics() *BucketStatistics {
	if m != nil {
		return m.BucketStatistics
	}
	return nil
}

func (m *ColumnStatistics) GetDecimalStatistics() *DecimalStatistics {
	if m != nil {
		return m.DecimalStatistics
	}
	return nil
}

func (m *ColumnStatistics) GetDateStatistics() *DateStatistics {
	if m != nil {
		return m.DateStatistics
	}
	return nil
}

func (m *ColumnStatistics) GetBinaryStatistics() *BinaryStatistics {
	if m != nil {
		return m.BinaryStatistics
	}
	return nil
}

func (m *ColumnStatistics) GetTimestampStatistics() *TimestampStatistics {
	if m != nil {
		return m.TimestampStatistics
	}
	return nil
}

func (m *ColumnStatistics) GetHasNull() bool {
	if m != nil && m.HasNull != nil {
		return *m.HasNull
	}
	return false
}

func (m *ColumnStatistics) GetBytesOnDisk() uint64 {
	if m != nil && m.BytesOnDisk != nil {
		return *m.BytesOnDisk
	}
	return 0
}

type RowIndexEntry struct {
	Positions            []uint64          `protobuf:"varint,1,rep,packed,name=positions" json:"positions,omitempty"`
	Statistics           *ColumnStatistics `protobuf:"bytes,2,opt,name=statistics" json:"statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RowIndexEntry) Reset()         { *m = RowIndexEntry{} }
func (m *RowIndexEntry) String() string { return proto.CompactTextString(m) }
func (*RowIndexEntry) ProtoMessage()    {}
func (*RowIndexEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{9}
}

func (m *RowIndexEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowIndexEntry.Unmarshal(m, b)
}
func (m *RowIndexEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowIndexEntry.Marshal(b, m, deterministic)
}
func (m *RowIndexEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowIndexEntry.Merge(m, src)
}
func (m *RowIndexEntry) XXX_Size() int {
	return xxx_messageInfo_RowIndexEntry.Size(m)
}
func (m *RowIndexEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_RowIndexEntry.DiscardUnknown(m)
}

var xxx_messageInfo_RowIndexEntry proto.InternalMessageInfo

func (m *RowIndexEntry) GetPositions() []uint64 {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *RowIndexEntry) GetStatistics() *ColumnStatistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

type RowIndex struct {
	Entry                []*RowIndexEntry `protobuf:"bytes,1,rep,name=entry" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RowIndex) Reset()         { *m = RowIndex{} }
func (m *RowIndex) String() string { return proto.CompactTextString(m) }
func (*RowIndex) ProtoMessage()    {}
func (*RowIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{10}
}

func (m *RowIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowIndex.Unmarshal(m, b)
}
func (m *RowIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowIndex.Marshal(b, m, deterministic)
}
func (m *RowIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowIndex.Merge(m, src)
}
func (m *RowIndex) XXX_Size() int {
	return xxx_messageInfo_RowIndex.Size(m)
}
func (m *RowIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_RowIndex.DiscardUnknown(m)
}

var xxx_messageInfo_RowIndex proto.InternalMessageInfo

func (m *RowIndex) GetEntry() []*RowIndexEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type BloomFilter struct {
	NumHashFunctions     *uint32  `protobuf:"varint,1,opt,name=numHashFunctions" json:"numHashFunctions,omitempty"`
	Bitset               []uint64 `protobuf:"fixed64,2,rep,name=bitset" json:"bitset,omitempty"`
	Utf8Bitset           []byte   `protobuf:"bytes,3,opt,name=utf8bitset" json:"utf8bitset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BloomFilter) Reset()         { *m = BloomFilter{} }
func (m *BloomFilter) String() string { return proto.CompactTextString(m) }
func (*BloomFilter) ProtoMessage()    {}
func (*BloomFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{11}
}

func (m *BloomFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BloomFilter.Unmarshal(m, b)
}
func (m *BloomFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BloomFilter.Marshal(b, m, deterministic)
}
func (m *BloomFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BloomFilter.Merge(m, src)
}
func (m *BloomFilter) XXX_Size() int {
	return xxx_messageInfo_BloomFilter.Size(m)
}
func (m *BloomFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_BloomFilter.DiscardUnknown(m)
}

var xxx_messageInfo_BloomFilter proto.InternalMessageInfo

func (m *BloomFilter) GetNumHashFunctions() uint32 {
	if m != nil && m.NumHashFunctions != nil {
		return *m.NumHashFunctions
	}
	return 0
}

func (m *BloomFilter) GetBitset() []uint64 {
	if m != nil {
		return m.Bitset
	}
	return nil
}

func (m *BloomFilter) GetUtf8Bitset() []byte {
	if m != nil {
		return m.Utf8Bitset
	}
	return nil
}

type BloomFilterIndex struct {
	BloomFilter          []*BloomFilter `protobuf:"bytes,1,rep,name=bloomFilter" json:"bloomFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BloomFilterIndex) Reset()         { *m = BloomFilterIndex{} }
func (m *BloomFilterIndex) String() string { return proto.CompactTextString(m) }
func (*BloomFilterIndex) ProtoMessage()    {}
func (*BloomFilterIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{12}
}

func (m *BloomFilterIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BloomFilterIndex.Unmarshal(m, b)
}
func (m *BloomFilterIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BloomFilterIndex.Marshal(b, m, deterministic)
}
func (m *BloomFilterIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BloomFilterIndex.Merge(m, src)
}
func (m *BloomFilterIndex) XXX_Size() int {
	return xxx_messageInfo_BloomFilterIndex.Size(m)
}
func (m *BloomFilterIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_BloomFilterIndex.DiscardUnknown(m)
}

var xxx_messageInfo_BloomFilterIndex proto.InternalMessageInfo

func (m *BloomFilterIndex) GetBloomFilter() []*BloomFilter {
	if m != nil {
		return m.BloomFilter
	}
	return nil
}

type Stream struct {
	Kind                 *Stream_Kind `protobuf:"varint,1,opt,name=kind,enum=orc.proto.Stream_Kind" json:"kind,omitempty"`
	Column               *uint32      `protobuf:"varint,2,opt,name=column" json:"column,omitempty"`
	Length               *uint64      `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{13}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetKind() Stream_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return Stream_PRESENT
}

func (m *Stream) GetColumn() uint32 {
	if m != nil && m.Column != nil {
		return *m.Column
	}
	return 0
}

func (m *Stream) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type ColumnEncoding struct {
	Kind           *ColumnEncoding_Kind `protobuf:"varint,1,opt,name=kind,enum=orc.proto.ColumnEncoding_Kind" json:"kind,omitempty"`
	DictionarySize *uint32              `protobuf:"varint,2,opt,name=dictionarySize" json:"dictionarySize,omitempty"`
	// The encoding of the bloom filters for this column:
	//   0 or missing = none or original
	//   1            = ORC-135 (utc for timestamps)
	BloomEncoding        *uint32  `protobuf:"varint,3,opt,name=bloomEncoding" json:"bloomEncoding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnEncoding) Reset()         { *m = ColumnEncoding{} }
func (m *ColumnEncoding) String() string { return proto.CompactTextString(m) }
func (*ColumnEncoding) ProtoMessage()    {}
func (*ColumnEncoding) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{14}
}

func (m *ColumnEncoding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnEncoding.Unmarshal(m, b)
}
func (m *ColumnEncoding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnEncoding.Marshal(b, m, deterministic)
}
func (m *ColumnEncoding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnEncoding.Merge(m, src)
}
func (m *ColumnEncoding) XXX_Size() int {
	return xxx_messageInfo_ColumnEncoding.Size(m)
}
func (m *ColumnEncoding) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnEncoding.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnEncoding proto.InternalMessageInfo

func (m *ColumnEncoding) GetKind() ColumnEncoding_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return ColumnEncoding_DIRECT
}

func (m *ColumnEncoding) GetDictionarySize() uint32 {
	if m != nil && m.DictionarySize != nil {
		return *m.DictionarySize
	}
	return 0
}

func (m *ColumnEncoding) GetBloomEncoding() uint32 {
	if m != nil && m.BloomEncoding != nil {
		return *m.BloomEncoding
	}
	return 0
}

type StripeFooter struct {
	Streams              []*Stream         `protobuf:"bytes,1,rep,name=streams" json:"streams,omitempty"`
	Columns              []*ColumnEncoding `protobuf:"bytes,2,rep,name=columns" json:"columns,omitempty"`
	WriterTimezone       *string           `protobuf:"bytes,3,opt,name=writerTimezone" json:"writerTimezone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StripeFooter) Reset()         { *m = StripeFooter{} }
func (m *StripeFooter) String() string { return proto.CompactTextString(m) }
func (*StripeFooter) ProtoMessage()    {}
func (*StripeFooter) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{15}
}

func (m *StripeFooter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StripeFooter.Unmarshal(m, b)
}
func (m *StripeFooter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StripeFooter.Marshal(b, m, deterministic)
}
func (m *StripeFooter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StripeFooter.Merge(m, src)
}
func (m *StripeFooter) XXX_Size() int {
	return xxx_messageInfo_StripeFooter.Size(m)
}
func (m *StripeFooter) XXX_DiscardUnknown() {
	xxx_messageInfo_StripeFooter.DiscardUnknown(m)
}

var xxx_messageInfo_StripeFooter proto.InternalMessageInfo

func (m *StripeFooter) GetStreams() []*Stream {
	if m != nil {
		return m.Streams
	}
	return nil
}

func (m *StripeFooter) GetColumns() []*ColumnEncoding {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *StripeFooter) GetWriterTimezone() string {
	if m != nil && m.WriterTimezone != nil {
		return *m.WriterTimezone
	}
	return ""
}

type Type struct {
	Kind                 *Type_Kind `protobuf:"varint,1,opt,name=kind,enum=orc.proto.Type_Kind" json:"kind,omitempty"`
	Subtypes             []uint32   `protobuf:"varint,2,rep,packed,name=subtypes" json:"subtypes,omitempty"`
	FieldNames           []string   `protobuf:"bytes,3,rep,name=fieldNames" json:"fieldNames,omitempty"`
	MaximumLength        *uint32    `protobuf:"varint,4,opt,name=maximumLength" json:"maximumLength,omitempty"`
	Precision            *uint32    `protobuf:"varint,5,opt,name=precision" json:"precision,omitempty"`
	Scale                *uint32    `protobuf:"varint,6,opt,name=scale" json:"scale,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Type) Reset()         { *m = Type{} }
func (m *Type) String() string { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()    {}
func (*Type) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{16}
}

func (m *Type) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Type.Unmarshal(m, b)
}
func (m *Type) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Type.Marshal(b, m, deterministic)
}
func (m *Type) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Type.Merge(m, src)
}
func (m *Type) XXX_Size() int {
	return xxx_messageInfo_Type.Size(m)
}
func (m *Type) XXX_DiscardUnknown() {
	xxx_messageInfo_Type.DiscardUnknown(m)
}

var xxx_messageInfo_Type proto.InternalMessageInfo

func (m *Type) GetKind() Type_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return Type_BOOLEAN
}

func (m *Type) GetSubtypes() []uint32 {
	if m != nil {
		return m.Subtypes
	}
	return nil
}

func (m *Type) GetFieldNames() []string {
	if m != nil {
		return m.FieldNames
	}
	return nil
}

func (m *Type) GetMaximumLength() uint32 {
	if m != nil && m.MaximumLength != nil {
		return *m.MaximumLength
	}
	return 0
}

func (m *Type) GetPrecision() uint32 {
	if m != nil && m.Precision != nil {
		return *m.Precision
	}
	return 0
}

func (m *Type) GetScale() uint32 {
	if m != nil && m.Scale != nil {
		return *m.Scale
	}
	return 0
}

type StripeInformation struct {
	Offset               *uint64  `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	IndexLength          *uint64  `protobuf:"varint,2,opt,name=indexLength" json:"indexLength,omitempty"`
	DataLength           *uint64  `protobuf:"varint,3,opt,name=dataLength" json:"dataLength,omitempty"`
	FooterLength         *uint64  `protobuf:"varint,4,opt,name=footerLength" json:"footerLength,omitempty"`
	NumberOfRows         *uint64  `protobuf:"varint,5,opt,name=numberOfRows" json:"numberOfRows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StripeInformation) Reset()         { *m = StripeInformation{} }
func (m *StripeInformation) String() string { return proto.CompactTextString(m) }
func (*StripeInformation) ProtoMessage()    {}
func (*StripeInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{17}
}

func (m *StripeInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StripeInformation.Unmarshal(m, b)
}
func (m *StripeInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StripeInformation.Marshal(b, m, deterministic)
}
func (m *StripeInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StripeInformation.Merge(m, src)
}
func (m *StripeInformation) XXX_Size() int {
	return xxx_messageInfo_StripeInformation.Size(m)
}
func (m *StripeInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_StripeInformation.DiscardUnknown(m)
}

var xxx_messageInfo_StripeInformation proto.InternalMessageInfo

func (m *StripeInformation) GetOffset() uint64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *StripeInformation) GetIndexLength() uint64 {
	if m != nil && m.IndexLength != nil {
		return *m.IndexLength
	}
	return 0
}

func (m *StripeInformation) GetDataLength() uint64 {
	if m != nil && m.DataLength != nil {
		return *m.DataLength
	}
	return 0
}

func (m *StripeInformation) GetFooterLength() uint64 {
	if m != nil && m.FooterLength != nil {
		return *m.FooterLength
	}
	return 0
}

func (m *StripeInformation) GetNumberOfRows() uint64 {
	if m != nil && m.NumberOfRows != nil {
		return *m.NumberOfRows
	}
	return 0
}

type UserMetadataItem struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMetadataItem) Reset()         { *m = UserMetadataItem{} }
func (m *UserMetadataItem) String() string { return proto.CompactTextString(m) }
func (*UserMetadataItem) ProtoMessage()    {}
func (*UserMetadataItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{18}
}

func (m *UserMetadataItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMetadataItem.Unmarshal(m, b)
}
func (m *UserMetadataItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMetadataItem.Marshal(b, m, deterministic)
}
func (m *UserMetadataItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMetadataItem.Merge(m, src)
}
func (m *UserMetadataItem) XXX_Size() int {
	return xxx_messageInfo_UserMetadataItem.Size(m)
}
func (m *UserMetadataItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMetadataItem.DiscardUnknown(m)
}

var xxx_messageInfo_UserMetadataItem proto.InternalMessageInfo

func (m *UserMetadataItem) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserMetadataItem) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StripeStatistics struct {
	ColStats             []*ColumnStatistics `protobuf:"bytes,1,rep,name=colStats" json:"colStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StripeStatistics) Reset()         { *m = StripeStatistics{} }
func (m *StripeStatistics) String() string { return proto.CompactTextString(m) }
func (*StripeStatistics) ProtoMessage()    {}
func (*StripeStatistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{19}
}

func (m *StripeStatistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StripeStatistics.Unmarshal(m, b)
}
func (m *StripeStatistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StripeStatistics.Marshal(b, m, deterministic)
}
func (m *StripeStatistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StripeStatistics.Merge(m, src)
}
func (m *StripeStatistics) XXX_Size() int {
	return xxx_messageInfo_StripeStatistics.Size(m)
}
func (m *StripeStatistics) XXX_DiscardUnknown() {
	xxx_messageInfo_StripeStatistics.DiscardUnknown(m)
}

var xxx_messageInfo_StripeStatistics proto.InternalMessageInfo

func (m *StripeStatistics) GetColStats() []*ColumnStatistics {
	if m != nil {
		return m.ColStats
	}
	return nil
}

type Metadata struct {
	StripeStats          []*StripeStatistics `protobuf:"bytes,1,rep,name=stripeStats" json:"stripeStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{20}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetStripeStats() []*StripeStatistics {
	if m != nil {
		return m.StripeStats
	}
	return nil
}

type Footer struct {
	HeaderLength   *uint64              `protobuf:"varint,1,opt,name=headerLength" json:"headerLength,omitempty"`
	ContentLength  *uint64              `protobuf:"varint,2,opt,name=contentLength" json:"contentLength,omitempty"`
	Stripes        []*StripeInformation `protobuf:"bytes,3,rep,name=stripes" json:"stripes,omitempty"`
	Types          []*Type              `protobuf:"bytes,4,rep,name=types" json:"types,omitempty"`
	Metadata       []*UserMetadataItem  `protobuf:"bytes,5,rep,name=metadata" json:"metadata,omitempty"`
	NumberOfRows   *uint64              `protobuf:"varint,6,opt,name=numberOfRows" json:"numberOfRows,omitempty"`
	Statistics     []*ColumnStatistics  `protobuf:"bytes,7,rep,name=statistics" json:"statistics,omitempty"`
	RowIndexStride *uint32              `protobuf:"varint,8,opt,name=rowIndexStride" json:"rowIndexStride,omitempty"`
	// Each implementation that writes ORC files should register for a code
	// 0 = ORC Java
	// 1 = ORC C++
	// 2 = Presto
	// 3 = Scritchley Go from https://github.com/scritchley/orc
	Writer               *uint32  `protobuf:"varint,9,opt,name=writer" json:"writer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Footer) Reset()         { *m = Footer{} }
func (m *Footer) String() string { return proto.CompactTextString(m) }
func (*Footer) ProtoMessage()    {}
func (*Footer) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{21}
}

func (m *Footer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Footer.Unmarshal(m, b)
}
func (m *Footer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Footer.Marshal(b, m, deterministic)
}
func (m *Footer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Footer.Merge(m, src)
}
func (m *Footer) XXX_Size() int {
	return xxx_messageInfo_Footer.Size(m)
}
func (m *Footer) XXX_DiscardUnknown() {
	xxx_messageInfo_Footer.DiscardUnknown(m)
}

var xxx_messageInfo_Footer proto.InternalMessageInfo

func (m *Footer) GetHeaderLength() uint64 {
	if m != nil && m.HeaderLength != nil {
		return *m.HeaderLength
	}
	return 0
}

func (m *Footer) GetContentLength() uint64 {
	if m != nil && m.ContentLength != nil {
		return *m.ContentLength
	}
	return 0
}

func (m *Footer) GetStripes() []*StripeInformation {
	if m != nil {
		return m.Stripes
	}
	return nil
}

func (m *Footer) GetTypes() []*Type {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Footer) GetMetadata() []*UserMetadataItem {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Footer) GetNumberOfRows() uint64 {
	if m != nil && m.NumberOfRows != nil {
		return *m.NumberOfRows
	}
	return 0
}

func (m *Footer) GetStatistics() []*ColumnStatistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

func (m *Footer) GetRowIndexStride() uint32 {
	if m != nil && m.RowIndexStride != nil {
		return *m.RowIndexStride
	}
	return 0
}

func (m *Footer) GetWriter() uint32 {
	if m != nil && m.Writer != nil {
		return *m.Writer
	}
	return 0
}

// Serialized length must be less that 255 bytes
type PostScript struct {
	FooterLength         *uint64          `protobuf:"varint,1,opt,name=footerLength" json:"footerLength,omitempty"`
	Compression          *CompressionKind `protobuf:"varint,2,opt,name=compression,enum=orc.proto.CompressionKind" json:"compression,omitempty"`
	CompressionBlockSize *uint64          `protobuf:"varint,3,opt,name=compressionBlockSize" json:"compressionBlockSize,omitempty"`
	// the version of the file format
	//   [0, 11] = Hive 0.11
	//   [0, 12] = Hive 0.12
	Version        []uint32 `protobuf:"varint,4,rep,packed,name=version" json:"version,omitempty"`
	MetadataLength *uint64  `protobuf:"varint,5,opt,name=metadataLength" json:"metadataLength,omitempty"`
	// The version of the writer that wrote the file. This number is
	// updated when we make fixes or large changes to the writer so that
	// readers can detect whether a given bug is present in the data.
	//
	// Only the Java ORC writer may use values under 6 (or missing) so that
	// readers that predate ORC-202 treat the new writers correctly. Each
	// writer should assign their own sequence of versions starting from 6.
	//
	// Version of the ORC Java writer:
	//   0 = original
	//   1 = HIVE-8732 fixed (fixed stripe/file maximum statistics &
	//                        string statistics use utf8 for min/max)
	//   2 = HIVE-4243 fixed (use real column names from Hive tables)
	//   3 = HIVE-12055 fixed (vectorized writer implementation)
	//   4 = HIVE-13083 fixed (decimals write present stream correctly)
	//   5 = ORC-101 fixed (bloom filters use utf8 consistently)
	//   6 = ORC-135 fixed (timestamp statistics use utc)
	//
	// Version of the ORC C++ writer:
	//   6 = original
	//
	// Version of the Presto writer:
	//   6 = original
	//
	// Version of the Scritchley Go writer:
	//   6 = original
	//
	WriterVersion *uint32 `protobuf:"varint,6,opt,name=writerVersion" json:"writerVersion,omitempty"`
	// Leave this last in the record
	Magic                *string  `protobuf:"bytes,8000,opt,name=magic" json:"magic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostScript) Reset()         { *m = PostScript{} }
func (m *PostScript) String() string { return proto.CompactTextString(m) }
func (*PostScript) ProtoMessage()    {}
func (*PostScript) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{22}
}

func (m *PostScript) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostScript.Unmarshal(m, b)
}
func (m *PostScript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostScript.Marshal(b, m, deterministic)
}
func (m *PostScript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostScript.Merge(m, src)
}
func (m *PostScript) XXX_Size() int {
	return xxx_messageInfo_PostScript.Size(m)
}
func (m *PostScript) XXX_DiscardUnknown() {
	xxx_messageInfo_PostScript.DiscardUnknown(m)
}

var xxx_messageInfo_PostScript proto.InternalMessageInfo

func (m *PostScript) GetFooterLength() uint64 {
	if m != nil && m.FooterLength != nil {
		return *m.FooterLength
	}
	return 0
}

func (m *PostScript) GetCompression() CompressionKind {
	if m != nil && m.Compression != nil {
		return *m.Compression
	}
	return CompressionKind_NONE
}

func (m *PostScript) GetCompressionBlockSize() uint64 {
	if m != nil && m.CompressionBlockSize != nil {
		return *m.CompressionBlockSize
	}
	return 0
}

func (m *PostScript) GetVersion() []uint32 {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *PostScript) GetMetadataLength() uint64 {
	if m != nil && m.MetadataLength != nil {
		return *m.MetadataLength
	}
	return 0
}

func (m *PostScript) GetWriterVersion() uint32 {
	if m != nil && m.WriterVersion != nil {
		return *m.WriterVersion
	}
	return 0
}

func (m *PostScript) GetMagic() string {
	if m != nil && m.Magic != nil {
		return *m.Magic
	}
	return ""
}

// The contents of the file tail that must be serialized.
// This gets serialized as part of OrcSplit, also used by footer cache.
type FileTail struct {
	Postscript           *PostScript `protobuf:"bytes,1,opt,name=postscript" json:"postscript,omitempty"`
	Footer               *Footer     `protobuf:"bytes,2,opt,name=footer" json:"footer,omitempty"`
	FileLength           *uint64     `protobuf:"varint,3,opt,name=fileLength" json:"fileLength,omitempty"`
	PostscriptLength     *uint64     `protobuf:"varint,4,opt,name=postscriptLength" json:"postscriptLength,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FileTail) Reset()         { *m = FileTail{} }
func (m *FileTail) String() string { return proto.CompactTextString(m) }
func (*FileTail) ProtoMessage()    {}
func (*FileTail) Descriptor() ([]byte, []int) {
	return fileDescriptor_725551812de63670, []int{23}
}

func (m *FileTail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileTail.Unmarshal(m, b)
}
func (m *FileTail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileTail.Marshal(b, m, deterministic)
}
func (m *FileTail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileTail.Merge(m, src)
}
func (m *FileTail) XXX_Size() int {
	return xxx_messageInfo_FileTail.Size(m)
}
func (m *FileTail) XXX_DiscardUnknown() {
	xxx_messageInfo_FileTail.DiscardUnknown(m)
}

var xxx_messageInfo_FileTail proto.InternalMessageInfo

func (m *FileTail) GetPostscript() *PostScript {
	if m != nil {
		return m.Postscript
	}
	return nil
}

func (m *FileTail) GetFooter() *Footer {
	if m != nil {
		return m.Footer
	}
	return nil
}

func (m *FileTail) GetFileLength() uint64 {
	if m != nil && m.FileLength != nil {
		return *m.FileLength
	}
	return 0
}

func (m *FileTail) GetPostscriptLength() uint64 {
	if m != nil && m.PostscriptLength != nil {
		return *m.PostscriptLength
	}
	return 0
}

func init() {
	proto.RegisterEnum("orc.proto.CompressionKind", CompressionKind_name, CompressionKind_value)
	proto.RegisterEnum("orc.proto.Stream_Kind", Stream_Kind_name, Stream_Kind_value)
	proto.RegisterEnum("orc.proto.ColumnEncoding_Kind", ColumnEncoding_Kind_name, ColumnEncoding_Kind_value)
	proto.RegisterEnum("orc.proto.Type_Kind", Type_Kind_name, Type_Kind_value)
	proto.RegisterType((*IntegerStatistics)(nil), "orc.proto.IntegerStatistics")
	proto.RegisterType((*DoubleStatistics)(nil), "orc.proto.DoubleStatistics")
	proto.RegisterType((*StringStatistics)(nil), "orc.proto.StringStatistics")
	proto.RegisterType((*BucketStatistics)(nil), "orc.proto.BucketStatistics")
	proto.RegisterType((*DecimalStatistics)(nil), "orc.proto.DecimalStatistics")
	proto.RegisterType((*DateStatistics)(nil), "orc.proto.DateStatistics")
	proto.RegisterType((*TimestampStatistics)(nil), "orc.proto.TimestampStatistics")
	proto.RegisterType((*BinaryStatistics)(nil), "orc.proto.BinaryStatistics")
	proto.RegisterType((*ColumnStatistics)(nil), "orc.proto.ColumnStatistics")
	proto.RegisterType((*RowIndexEntry)(nil), "orc.proto.RowIndexEntry")
	proto.RegisterType((*RowIndex)(nil), "orc.proto.RowIndex")
	proto.RegisterType((*BloomFilter)(nil), "orc.proto.BloomFilter")
	proto.RegisterType((*BloomFilterIndex)(nil), "orc.proto.BloomFilterIndex")
	proto.RegisterType((*Stream)(nil), "orc.proto.Stream")
	proto.RegisterType((*ColumnEncoding)(nil), "orc.proto.ColumnEncoding")
	proto.RegisterType((*StripeFooter)(nil), "orc.proto.StripeFooter")
	proto.RegisterType((*Type)(nil), "orc.proto.Type")
	proto.RegisterType((*StripeInformation)(nil), "orc.proto.StripeInformation")
	proto.RegisterType((*UserMetadataItem)(nil), "orc.proto.UserMetadataItem")
	proto.RegisterType((*StripeStatistics)(nil), "orc.proto.StripeStatistics")
	proto.RegisterType((*Metadata)(nil), "orc.proto.Metadata")
	proto.RegisterType((*Footer)(nil), "orc.proto.Footer")
	proto.RegisterType((*PostScript)(nil), "orc.proto.PostScript")
	proto.RegisterType((*FileTail)(nil), "orc.proto.FileTail")
}

func init() { proto.RegisterFile("orc_proto.proto", fileDescriptor_725551812de63670) }

var fileDescriptor_725551812de63670 = []byte{
	// 1665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xe3, 0xc8,
	0x11, 0x0e, 0x25, 0xea, 0xaf, 0x64, 0xc9, 0xad, 0x1e, 0xcf, 0x42, 0x49, 0x06, 0x86, 0x41, 0x6c,
	0x16, 0xce, 0x24, 0xf0, 0x41, 0xf9, 0x1b, 0x24, 0x9b, 0x00, 0xfa, 0xa1, 0xc7, 0xcc, 0xca, 0xa4,
	0xd1, 0xa2, 0x9d, 0xf5, 0x5c, 0x0c, 0x8a, 0x6a, 0xdb, 0x84, 0xf9, 0x17, 0x92, 0x5a, 0xaf, 0xf7,
	0x98, 0x5b, 0x90, 0x17, 0x08, 0x10, 0x20, 0xb7, 0x3c, 0x42, 0x80, 0xdc, 0x92, 0x57, 0xc8, 0x2d,
	0x8f, 0x13, 0x74, 0x37, 0x25, 0x35, 0x49, 0x7b, 0x72, 0xc8, 0x5e, 0x04, 0xf6, 0x57, 0xd5, 0xa5,
	0xea, 0xaf, 0xbe, 0xaa, 0x6e, 0xd8, 0x8f, 0x12, 0xf7, 0x26, 0x4e, 0xa2, 0x2c, 0x3a, 0xe1, 0xbf,
	0xb8, 0x13, 0x25, 0xae, 0xf8, 0xd4, 0xae, 0x61, 0x60, 0x84, 0x19, 0xbd, 0xa3, 0xc9, 0x22, 0x73,
	0x32, 0x2f, 0xcd, 0x3c, 0x37, 0xc5, 0x43, 0x68, 0x05, 0x5e, 0xe8, 0x05, 0xeb, 0x60, 0xa8, 0x1c,
	0x29, 0xc7, 0x98, 0x6c, 0x96, 0xdc, 0xe2, 0x7c, 0xcd, 0x2d, 0xb5, 0xdc, 0x22, 0x96, 0x18, 0x41,
	0x3d, 0x5d, 0x07, 0xc3, 0x3a, 0x47, 0xd9, 0xa7, 0xf6, 0x25, 0xa0, 0x59, 0xb4, 0x5e, 0xfa, 0xf4,
	0xe5, 0xc8, 0xca, 0x8b, 0x91, 0x95, 0x67, 0x23, 0x2b, 0x22, 0xf2, 0x9f, 0x15, 0x40, 0x8b, 0x2c,
	0xf1, 0xc2, 0xbb, 0x97, 0x43, 0x77, 0x5e, 0x0c, 0xdd, 0xf9, 0x48, 0xd2, 0xf8, 0x10, 0xc0, 0x8f,
	0x1e, 0x69, 0x32, 0x89, 0xd6, 0xe1, 0x6a, 0xa8, 0x72, 0x77, 0x09, 0x61, 0xf6, 0x75, 0x1c, 0x6f,
	0xec, 0x0d, 0x61, 0xdf, 0x21, 0xda, 0x8f, 0x01, 0x4d, 0xd6, 0xee, 0x03, 0xcd, 0x0a, 0x99, 0x35,
	0xdc, 0x68, 0x1d, 0x66, 0x43, 0xe5, 0xa8, 0x7e, 0xac, 0x4e, 0x6a, 0x48, 0x21, 0x02, 0x60, 0xec,
	0xcf, 0xa8, 0xeb, 0x05, 0x8e, 0xff, 0xed, 0x1d, 0xa4, 0x23, 0x38, 0x9a, 0x41, 0x7f, 0xe6, 0x64,
	0x1f, 0xe1, 0x7e, 0xf0, 0x62, 0xdc, 0xc1, 0x36, 0xae, 0xf6, 0x47, 0x05, 0x5e, 0xd9, 0x5e, 0x40,
	0xd3, 0xcc, 0x09, 0xe2, 0xff, 0x53, 0x21, 0x87, 0x00, 0xb9, 0xd3, 0x65, 0xe6, 0xe6, 0x9c, 0x4b,
	0x08, 0xb7, 0x0b, 0x57, 0x66, 0x57, 0x73, 0xfb, 0x16, 0xd1, 0x3e, 0x05, 0x34, 0xf1, 0x42, 0x27,
	0x79, 0x92, 0xf2, 0xc8, 0xcf, 0xad, 0xec, 0x54, 0xf7, 0xcf, 0x06, 0xa0, 0x69, 0xe4, 0xaf, 0x83,
	0x50, 0x72, 0xfb, 0x0c, 0xfa, 0xe1, 0x3a, 0x58, 0xd2, 0xc4, 0xba, 0xbd, 0x72, 0xfc, 0x35, 0x4d,
	0xf9, 0x0e, 0x95, 0x94, 0x50, 0x3c, 0x81, 0x9e, 0x17, 0x4a, 0xa5, 0xe3, 0x47, 0xe8, 0x8e, 0xde,
	0x9c, 0x6c, 0x1b, 0xe6, 0xa4, 0xd2, 0x2d, 0xa4, 0xb8, 0x05, 0xbf, 0x07, 0xb4, 0x2a, 0xc9, 0x9e,
	0x1f, 0xb6, 0x3b, 0xfa, 0xbe, 0x14, 0xa6, 0xdc, 0x19, 0xa4, 0xb2, 0x89, 0x05, 0x4a, 0x4b, 0x22,
	0xe7, 0xac, 0x14, 0x03, 0x95, 0xfb, 0x80, 0x54, 0x36, 0xb1, 0x40, 0xcb, 0x92, 0x26, 0xb9, 0x72,
	0x8b, 0x81, 0xca, 0xb2, 0x25, 0x95, 0x4d, 0xf8, 0xb7, 0x30, 0x58, 0x95, 0xe5, 0x3a, 0x6c, 0x56,
	0x28, 0xaa, 0x48, 0x9a, 0x54, 0xb7, 0xe1, 0x31, 0xf4, 0x57, 0x05, 0x7d, 0x0e, 0x5b, 0x3c, 0xd0,
	0x77, 0xe5, 0x40, 0x05, 0x07, 0x52, 0xda, 0xc0, 0xcf, 0x55, 0x12, 0xc4, 0xb0, 0x5d, 0x3d, 0x57,
	0xc9, 0x85, 0x54, 0x36, 0xe1, 0x0b, 0x78, 0x95, 0x55, 0x45, 0x3e, 0xec, 0xf0, 0x58, 0x87, 0x52,
	0xac, 0x67, 0x5a, 0x81, 0x3c, 0xb7, 0x95, 0x75, 0xc1, 0xbd, 0x93, 0x9a, 0x6b, 0xdf, 0x1f, 0xc2,
	0x91, 0x72, 0xdc, 0x26, 0x9b, 0x25, 0x3e, 0x82, 0xee, 0xf2, 0x29, 0xa3, 0xa9, 0x15, 0xce, 0xbc,
	0xf4, 0x61, 0xd8, 0xe5, 0x3a, 0x94, 0x21, 0x2d, 0x84, 0x1e, 0x89, 0x1e, 0x8d, 0x70, 0x45, 0xbf,
	0xd6, 0xc3, 0x2c, 0x79, 0xc2, 0x47, 0xd0, 0x89, 0xa3, 0xd4, 0xcb, 0xbc, 0x28, 0x4c, 0xa5, 0x19,
	0xb2, 0x03, 0xf1, 0xaf, 0x00, 0xd2, 0xb2, 0x68, 0x65, 0x0e, 0xca, 0x0d, 0x41, 0x24, 0x77, 0xed,
	0x97, 0xd0, 0xde, 0xfc, 0x1f, 0x3e, 0x81, 0x06, 0x65, 0xff, 0xc9, 0xff, 0xa6, 0x3b, 0x1a, 0x4a,
	0x31, 0x0a, 0x39, 0x11, 0xe1, 0xa6, 0xfd, 0x1e, 0xba, 0x13, 0x3f, 0x8a, 0x82, 0x53, 0xcf, 0xcf,
	0x68, 0x82, 0xdf, 0x02, 0x0a, 0xd7, 0xc1, 0x99, 0x93, 0xde, 0x9f, 0xae, 0x43, 0x77, 0x93, 0xb0,
	0x72, 0xdc, 0x23, 0x15, 0x1c, 0x7f, 0x02, 0xcd, 0xa5, 0x97, 0xa5, 0x34, 0x1b, 0xd6, 0x8e, 0xea,
	0xc7, 0x4d, 0x92, 0xaf, 0xf8, 0x84, 0xcd, 0x6e, 0xdf, 0xe5, 0x36, 0xd6, 0x39, 0x7b, 0x44, 0x42,
	0xb4, 0x39, 0x20, 0xe9, 0x2f, 0x45, 0xda, 0xef, 0xa0, 0xbb, 0xdc, 0x61, 0x79, 0xf2, 0x9f, 0xc8,
	0x22, 0xd8, 0x59, 0x89, 0xec, 0xaa, 0xfd, 0xa1, 0x06, 0xcd, 0x45, 0x96, 0x50, 0x27, 0xc0, 0x6f,
	0x41, 0x7d, 0xf0, 0xc2, 0x15, 0x4f, 0xb8, 0x5f, 0xd8, 0x2d, 0x1c, 0x4e, 0xbe, 0xf0, 0xc2, 0x15,
	0xe1, 0x3e, 0x2c, 0x79, 0x97, 0x73, 0xca, 0xc9, 0xee, 0x91, 0x7c, 0xc5, 0x70, 0x9f, 0x86, 0x77,
	0xd9, 0x3d, 0x4f, 0x5c, 0x25, 0xf9, 0x4a, 0xfb, 0x8b, 0x02, 0x2a, 0xdb, 0x8e, 0xbb, 0xd0, 0xba,
	0x20, 0xfa, 0x42, 0x37, 0x6d, 0xf4, 0x1d, 0xdc, 0x06, 0x75, 0x36, 0xb6, 0xc7, 0x48, 0xc1, 0x00,
	0xcd, 0xb9, 0x6e, 0xbe, 0xb7, 0xcf, 0x50, 0x0d, 0xbf, 0x82, 0xfd, 0x99, 0x31, 0xb5, 0x0d, 0xcb,
	0x1c, 0x93, 0xeb, 0x1b, 0xee, 0x50, 0xc7, 0x07, 0x80, 0x24, 0x70, 0x6a, 0x5d, 0x9a, 0x36, 0x52,
	0x71, 0x0f, 0x3a, 0x0b, 0x7d, 0x6a, 0x99, 0xb3, 0x31, 0xb9, 0x46, 0x0d, 0xb6, 0x24, 0xd6, 0xef,
	0x6e, 0x0c, 0x73, 0xa6, 0x7f, 0x89, 0x9a, 0x18, 0xc1, 0xde, 0x64, 0x6e, 0x59, 0xe7, 0x37, 0xa7,
	0xc6, 0xdc, 0xd6, 0x09, 0x6a, 0xe1, 0xd7, 0x30, 0x90, 0x91, 0x9b, 0x4b, 0xfb, 0xf4, 0x1d, 0x6a,
	0x6b, 0xff, 0x51, 0xa0, 0x2f, 0x24, 0xa2, 0x87, 0x6e, 0xb4, 0xf2, 0xc2, 0x3b, 0x3c, 0x2a, 0x90,
	0x71, 0x58, 0xd1, 0xd2, 0xc6, 0x51, 0x26, 0xe5, 0x33, 0xe8, 0xaf, 0x3c, 0x5e, 0x5d, 0xd6, 0x5e,
	0xde, 0x37, 0x34, 0x27, 0xa7, 0x84, 0xe2, 0x4f, 0xa1, 0xc7, 0x4b, 0xb0, 0x89, 0xc1, 0xb9, 0xea,
	0x91, 0x22, 0xa8, 0xcd, 0x72, 0xc6, 0x00, 0x9a, 0x33, 0x83, 0xe8, 0x53, 0x46, 0x58, 0x1f, 0x60,
	0xc7, 0x02, 0x52, 0xd8, 0x81, 0x85, 0xed, 0xe6, 0x6a, 0x84, 0x6a, 0x78, 0x00, 0x3d, 0x89, 0xa4,
	0xab, 0x11, 0xaa, 0xb3, 0xa7, 0xc2, 0x1e, 0x1b, 0x91, 0x31, 0x3d, 0x8d, 0x22, 0x26, 0xd1, 0x1f,
	0x41, 0x2b, 0xe5, 0xe5, 0x4c, 0x73, 0x99, 0x0c, 0x2a, 0x85, 0x26, 0x1b, 0x0f, 0xfc, 0x13, 0x68,
	0x89, 0xc2, 0xa6, 0x5c, 0xa4, 0xc5, 0xe9, 0x54, 0x24, 0x82, 0x6c, 0x3c, 0x19, 0x0d, 0x8f, 0x89,
	0x97, 0xd1, 0x84, 0x4d, 0x8b, 0x6f, 0xa2, 0x90, 0xe6, 0xd7, 0x72, 0x09, 0xd5, 0xfe, 0x5a, 0x07,
	0xd5, 0x7e, 0x8a, 0x29, 0x3e, 0x2e, 0x70, 0x7d, 0x20, 0xcf, 0x9b, 0xa7, 0x98, 0xca, 0x0c, 0x1f,
	0x42, 0x3b, 0x5d, 0x2f, 0xb3, 0xa7, 0x98, 0x8a, 0x84, 0x7a, 0x7c, 0x10, 0x6c, 0x31, 0xd6, 0x3b,
	0xb7, 0x1e, 0xf5, 0x57, 0xa6, 0x13, 0x50, 0x76, 0xeb, 0xd4, 0xd9, 0xeb, 0x64, 0x87, 0x30, 0xe6,
	0xf3, 0x0b, 0x75, 0x2e, 0x54, 0xaa, 0x0a, 0xe6, 0x0b, 0x20, 0x7e, 0x03, 0x9d, 0x38, 0xa1, 0xae,
	0x97, 0x7a, 0x51, 0xc8, 0x2f, 0x8a, 0x1e, 0xd9, 0x01, 0xf8, 0x00, 0x1a, 0xa9, 0xeb, 0xf8, 0x94,
	0x0f, 0xfe, 0x1e, 0x11, 0x0b, 0xed, 0xdf, 0x92, 0xc0, 0x27, 0x96, 0x35, 0xd7, 0xc7, 0xa6, 0x10,
	0xf8, 0xe4, 0xda, 0xd6, 0x91, 0x82, 0x3b, 0xd0, 0x58, 0x9c, 0x59, 0xc4, 0x46, 0x35, 0xdc, 0x82,
	0xba, 0x61, 0xda, 0xa8, 0xce, 0xac, 0x73, 0xcb, 0x7c, 0x8f, 0x54, 0x66, 0x3d, 0x9d, 0x5b, 0x63,
	0x1b, 0x35, 0x78, 0xb9, 0xad, 0xcb, 0xc9, 0x5c, 0x47, 0x4d, 0xf6, 0xbd, 0xb0, 0x89, 0x61, 0xbe,
	0x47, 0x2d, 0xf6, 0x3d, 0x31, 0x78, 0xd9, 0xdb, 0xac, 0xec, 0xb6, 0x71, 0xae, 0x2f, 0xec, 0xf1,
	0xf9, 0x05, 0xea, 0xf0, 0x38, 0xc6, 0xc2, 0x46, 0xc0, 0x42, 0x9f, 0x8f, 0x2f, 0x50, 0x37, 0xdf,
	0x79, 0x39, 0xb5, 0xd1, 0x1e, 0x0b, 0x7e, 0x69, 0x1a, 0x96, 0x89, 0x7a, 0x2c, 0xb9, 0x99, 0x3e,
	0x35, 0xce, 0xc7, 0x73, 0xd4, 0xcf, 0xbb, 0x4f, 0x47, 0xfb, 0x0c, 0xbe, 0x1a, 0x93, 0xe9, 0xd9,
	0x98, 0x20, 0xc4, 0x60, 0xfe, 0x35, 0xd0, 0xfe, 0xae, 0xc0, 0x40, 0x68, 0xc7, 0x08, 0x6f, 0xa3,
	0x24, 0x70, 0x98, 0x88, 0x59, 0x8b, 0x47, 0xb7, 0xb7, 0x6c, 0x36, 0x89, 0x37, 0x44, 0xbe, 0x62,
	0x83, 0xdd, 0x63, 0xc3, 0x28, 0x67, 0xb6, 0x26, 0x06, 0xbb, 0x04, 0xb1, 0xea, 0xac, 0x9c, 0xcc,
	0x99, 0xcb, 0x03, 0x42, 0x42, 0xb0, 0x06, 0x7b, 0xb7, 0x5c, 0xa4, 0x52, 0x71, 0x54, 0x52, 0xc0,
	0x98, 0xcf, 0xe6, 0xcd, 0x42, 0xa2, 0x47, 0x71, 0x8f, 0xab, 0xa4, 0x80, 0x69, 0x9f, 0x03, 0xba,
	0x4c, 0x69, 0x72, 0x4e, 0x33, 0x87, 0x45, 0x37, 0x32, 0x1a, 0x60, 0x0c, 0x6a, 0xe8, 0x04, 0x34,
	0x7f, 0x51, 0xf2, 0x6f, 0x56, 0xc9, 0xaf, 0xd8, 0xbb, 0x87, 0xe7, 0xba, 0x47, 0xc4, 0x42, 0xfb,
	0x42, 0xbc, 0xad, 0x63, 0xf9, 0xa6, 0xfd, 0x05, 0xb4, 0xdd, 0x88, 0xdf, 0xde, 0x9b, 0xae, 0xf9,
	0xe8, 0xed, 0xb2, 0x75, 0xd6, 0x0c, 0x68, 0x6f, 0xd2, 0xc0, 0xbf, 0x86, 0x6e, 0xba, 0x0d, 0xfc,
	0x5c, 0x9c, 0xf2, 0xdf, 0x12, 0xd9, 0x5f, 0xfb, 0x53, 0x1d, 0x9a, 0x79, 0x0f, 0x6b, 0xb0, 0x77,
	0x4f, 0x9d, 0xd5, 0x96, 0x28, 0x51, 0x88, 0x02, 0xc6, 0xa4, 0xee, 0x46, 0x61, 0x46, 0xc3, 0xac,
	0x50, 0x90, 0x22, 0x88, 0x7f, 0xce, 0xa7, 0x81, 0x17, 0xe7, 0xdd, 0x52, 0x7c, 0xc7, 0x54, 0x6a,
	0x4f, 0x36, 0xce, 0xf8, 0x07, 0xd0, 0x10, 0x5d, 0xa8, 0xf2, 0x5d, 0xfb, 0xa5, 0x9e, 0x25, 0xc2,
	0xca, 0x78, 0x0b, 0xf2, 0xe3, 0x0f, 0x1b, 0x95, 0xf3, 0x96, 0x8b, 0x44, 0xb6, 0xce, 0x95, 0x32,
	0x37, 0xab, 0x65, 0x2e, 0x5d, 0xfa, 0xad, 0xff, 0x5d, 0x16, 0xc9, 0x9d, 0x0d, 0xa9, 0x24, 0xbf,
	0xd0, 0xd9, 0x31, 0x57, 0x94, 0xbf, 0x9c, 0x7a, 0xa4, 0x84, 0x32, 0xb5, 0x8b, 0xb1, 0xc5, 0x5f,
	0x43, 0x3d, 0x92, 0xaf, 0xb4, 0xbf, 0xd5, 0x00, 0x2e, 0xa2, 0x34, 0x5b, 0xb8, 0x89, 0x17, 0x67,
	0x15, 0xe9, 0x2a, 0xcf, 0x48, 0xf7, 0x73, 0xe8, 0xba, 0x51, 0x10, 0x27, 0x34, 0xe5, 0x83, 0xa5,
	0xc6, 0xa7, 0xdd, 0xf7, 0x0a, 0x09, 0x6f, 0xad, 0x7c, 0xe6, 0xc9, 0xee, 0x78, 0x04, 0x07, 0xd2,
	0x72, 0xe2, 0x47, 0xee, 0x03, 0xbf, 0x62, 0x44, 0x1b, 0x3d, 0x6b, 0xc3, 0x6f, 0xa0, 0xf5, 0x15,
	0x4d, 0xf8, 0xbf, 0xa9, 0xdb, 0x69, 0xb9, 0x81, 0x18, 0x05, 0x1b, 0xbe, 0xf3, 0xac, 0x45, 0x33,
	0x95, 0x50, 0xa6, 0x24, 0x71, 0xe8, 0xab, 0x3c, 0x96, 0x18, 0x7c, 0x45, 0x10, 0xbf, 0x86, 0x46,
	0xe0, 0xdc, 0x79, 0xee, 0xf0, 0x5f, 0xbf, 0xe1, 0x2d, 0x26, 0x56, 0xda, 0x3f, 0x14, 0x68, 0x9f,
	0x7a, 0x3e, 0xb5, 0x1d, 0xcf, 0xc7, 0x3f, 0x03, 0x88, 0xa3, 0x34, 0x4b, 0x39, 0x67, 0x9c, 0xa3,
	0xee, 0xe8, 0xb5, 0x44, 0xc0, 0x8e, 0x50, 0x22, 0x39, 0xe2, 0x1f, 0x42, 0x53, 0x10, 0x99, 0xbf,
	0xec, 0xe4, 0x1b, 0x4b, 0x74, 0x04, 0xc9, 0x1d, 0xc4, 0x05, 0xe0, 0xd3, 0xe2, 0x88, 0xd9, 0x21,
	0xec, 0x81, 0xb6, 0x0b, 0x5c, 0x18, 0x33, 0x15, 0xfc, 0xed, 0x39, 0xec, 0x97, 0x2a, 0xc2, 0x66,
	0xa3, 0x69, 0x99, 0xba, 0x98, 0xec, 0x1f, 0xe6, 0xc6, 0x44, 0x3c, 0x5d, 0x16, 0xe6, 0xf8, 0xe2,
	0xe2, 0x5a, 0x8c, 0xf6, 0xf9, 0x07, 0x0b, 0xd5, 0xc5, 0xc7, 0x4f, 0x91, 0xca, 0xfd, 0x16, 0xf6,
	0x0c, 0x35, 0x26, 0x07, 0xd0, 0x8f, 0x92, 0xbb, 0x13, 0x27, 0x76, 0xdc, 0x7b, 0xca, 0x4e, 0xf0,
	0xa1, 0x16, 0x2f, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x56, 0xa7, 0xc9, 0x9c, 0x10, 0x00,
	0x00,
}
